
project_id = "rqwrvkkfixrogxogunsk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[functions]
[functions.send-email]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.edit-field]
verify_jwt = false

[functions.forward-pdf]
verify_jwt = false

[functions.get-gmail-credentials]
verify_jwt = false
